import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import Hero from '/components/hero-image'
import Navbar from '/components/navbar'
import Footer from '/components/footer'
import utilStyles from '../styles/articles.module.css'
import { getSortedPostsData } from '../lib/posts'
import Date from '../components/date'


export async function getStaticProps() {
  const allPostsData = getSortedPostsData()

  return {
    props: {
      allPostsData
    }
  }
}

export default function Home({ allPostsData }) {
  return (
    <>

      <Head>
        <title>Entre Mates Te Conté</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <header>
        <Navbar/>
      </header>
      <Hero/>
      <div className="container">
        <main className={styles.main}>
          <br></br>
          <section className={`${utilStyles.headingMd} ${utilStyles.padding1px}`}>
            <h1 id="articulos">Artículos y entrevistas</h1><br />
            <ul className={utilStyles.list}>
              {allPostsData.map(({ id, date, title }) => (
                <li className={utilStyles.listItem} key={id}>
                  <Link href={`/posts/${id}`}>
                    <a>{title}</a>
                  </Link>
                  <br />
                  <small className={utilStyles.lightText}>
                    <Date dateString={date} />
                  </small>
                </li>
              ))}
            </ul>
          </section>
        </main>
      </div>
      <footer id="footer">
        <Footer/>
      </footer>
    </>

  )
}
